# Generated by Django 5.1.1 on 2024-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeavendor',
            name='company_category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Cosmetics', 'Cosmetics'), ('Health', 'Health'), ('Kitchen', 'Kitchen'), ('Clothes', 'Clothes'), ('Kitchen', 'Kitchen'), ('Toys & Games', 'Toys & Games'), ('Others', 'Others')], default='electronics', max_length=50),
            preserve_default=False,
        ),
    ]
