# Generated by Django 5.1.1 on 2024-10-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_becomeavendor_company_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomeavendor',
            old_name='company_location',
            new_name='company_state',
        ),
    ]
