# Generated by Django 5.1.1 on 2024-10-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_company_location_becomeavendor_company_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeavendor',
            name='company_cac',
            field=models.FileField(upload_to='become-a-vendor'),
        ),
        migrations.AlterField(
            model_name='becomeavendor',
            name='company_category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Cosmetics', 'Cosmetics'), ('Health', 'Health'), ('Kitchen', 'Kitchen'), ('Clothes', 'Clothes'), ('Kitchen', 'Kitchen'), ('Toys & Games', 'Toys & Games'), ('Others', 'Others')], help_text='Choose Category *', max_length=50),
        ),
    ]
