# Generated by Django 5.1.1 on 2024-10-11 12:15

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_becomeavendor_company_cac_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomeavendor',
            options={'verbose_name_plural': 'Vendors'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, help_text='in %', null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 500], upload_to='products')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.becomeavendor')),
            ],
        ),
    ]
