# Generated by Django 5.1.1 on 2024-10-11 12:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_becomeavendor_options_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeavendor',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='2349121516274', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
