# Generated by Django 5.1.1 on 2024-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_becomeavendor_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refund_policy',
            field=models.TextField(default='something something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(default='something something'),
            preserve_default=False,
        ),
    ]
