# Generated by Django 5.1.1 on 2024-10-19 13:16

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_refund_policy_product_return_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('BRONZE', 'Bronze'), ('GRAY', 'Gray'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('SILVER', 'Silver'), ('WHITE', 'White')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 500], upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('XXXL', 'Extra Extra Extra Large')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trouser_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colourS',
            field=models.ManyToManyField(to='shop.colour'),
        ),
    ]
