# Generated by Django 5.1.1 on 2024-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_colour_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colourS',
        ),
        migrations.AddField(
            model_name='product',
            name='colours',
            field=models.ManyToManyField(to='shop.colour'),
        ),
    ]
