# Generated by Django 5.1.1 on 2024-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_colours_product_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeavendor',
            name='company_logo',
            field=models.ImageField(default='shop\\static\\images\\SmartSelect_20240210_131049_Chrome.jpg', upload_to='vendors'),
            preserve_default=False,
        ),
    ]
