# Generated by Django 5.1.1 on 2024-10-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_becomeavendor_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeavendor',
            name='company_state',
            field=models.CharField(choices=[('AbiaAdamawaAkwa', 'Abiaadamawaakwa'), ('IbomAnambraBauchiBayelsaBenueBornoCross', 'Ibomanambrabauchibayelsabenuebornocross'), ('RiverDeltaEbonyiEdoEkitiEnuguFCT', 'Riverdeltaebonyiedoekitienugufct'), ('-', '-'), ('AbujaGombeImoJigawaKadunaKanoKatsinaKebbiKogiKwaraLagosNasarawaNigerOgunOndoOsunOyoPlateauRiversSokotoTarabaYobeZamfara', 'Abujagombeimojigawakadunakanokatsinakebbikogikwaralagosnasarawanigerogunondoosunoyoplateauriverssokototarabayobezamfara')], max_length=150),
        ),
    ]
