# Generated by Django 5.1.1 on 2024-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_becomeavendor_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeavendor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
