# Generated by Django 5.1.1 on 2024-11-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_becomeavendor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.becomeavendor')),
            ],
        ),
    ]
