# Generated by Django 5.1.1 on 2024-11-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_size_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
    ]
