# Generated by Django 5.1.1 on 2024-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeavendor',
            name='company_description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque felis. Vel pretium lectus quam id leo in vitae turpis massa. Nunc id cursus metus aliquam. Libero id faucibus nisl tincidunt eget. Aliquam id diam maecenas ultricies mi eget mauris. Volutpat ac tincidunt vitae semper quis lectus. Vestibulum mattis ullamcorper velit sed. A arcu cursus vitae congue mauris.'),
            preserve_default=False,
        ),
    ]
