# Generated by Django 5.1.1 on 2024-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_becomeavendor_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_stars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
