# Generated by Django 5.1.1 on 2024-11-16 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productrating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
