# Generated by Django 5.1.1 on 2024-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_productrating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='review_stars',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
