# Generated by Django 5.1.1 on 2024-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_productrating_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='avg_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
