# Generated by Django 5.1.1 on 2024-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productrating_avg_rating_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='avg_rating_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
