# Generated by Django 5.1.1 on 2024-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_productrating_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='total_reviews',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
