# Generated by Django 5.1.1 on 2024-11-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_productrating_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='total_reviews',
        ),
    ]
