# Generated by Django 5.1.1 on 2024-11-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderItem',
            new_name='order_item',
        ),
    ]
