# Generated by Django 5.1.1 on 2024-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
