# Generated by Django 5.1.1 on 2024-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_address_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
