# Generated by Django 5.1.1 on 2024-12-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_orders_delivered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
