# Generated by Django 5.1.1 on 2024-12-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_orderitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
    ]
