# Generated by Django 5.1.1 on 2024-12-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_orderitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.becomeavendor', verbose_name='vendor'),
        ),
    ]
