# Generated by Django 5.1.1 on 2024-12-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_orderitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
    ]
