# Generated by Django 5.1.1 on 2024-12-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_orderitem_colour_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Colour',
            new_name='colour',
        ),
    ]
