# Generated by Django 5.1.1 on 2024-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_rename_colour_orderitem_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
