# Generated by Django 5.1.1 on 2024-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_address_first_name_address_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='vendor_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
