# Generated by Django 5.1.1 on 2025-01-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_orders_vendor_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
