# Generated by Django 5.1.1 on 2025-01-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='product',
        ),
    ]
