# Generated by Django 5.1.1 on 2025-01-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_payments_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(default='sulaiman@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
