# Generated by Django 5.1.1 on 2025-01-23 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_payments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 21, 54, 44, 345285, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
