# Generated by Django 5.1.1 on 2025-01-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_orders_ordered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_on',
        ),
    ]
