# Generated by Django 5.1.1 on 2025-01-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeavendor',
            name='company_account_name',
            field=models.CharField(default='SULAIMAN IBRAHIM', max_length=105),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becomeavendor',
            name='company_account_number',
            field=models.IntegerField(default='0217442856'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becomeavendor',
            name='company_bank',
            field=models.CharField(default='Guaranty Trust Bank', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='sub_account_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
