# Generated by Django 5.1.1 on 2025-01-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_becomeavendor_company_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='sub_account_ID',
        ),
        migrations.AddField(
            model_name='becomeavendor',
            name='sub_account_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
