# Generated by Django 5.1.1 on 2025-01-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_remove_payments_sub_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeavendor',
            name='company_account_number',
            field=models.CharField(max_length=10),
        ),
    ]
