# Generated by Django 5.1.1 on 2025-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_becomeavendor_company_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='sub_account_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
